- hosts: iosxr
  gather_facts: no
  connection: local

  tasks:
      - name: configure interface settings
        iosxr_config:
         lines:
           - description SHIMA
           - ip address 192.168.0.1 255.255.255.0
           - vrf SHIMA
           - service-policy input SHIMA
           - ipv4 address 10.0.0.1 255.255.255.0
         parents: interface gi0/0/0/0

